import { Product } from '@/components/product'

// Mock data for development (prices in INR)
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Recycled Hoodie',
    slug: 'recycled-hoodie',
    price: 4999,
    compareAtPrice: undefined,
    images: ['/images/products/hoodie-1.jpg', '/images/products/hoodie-2.jpg'],
    category: 'hoodies',
    colors: ['Black', 'Charcoal', 'Forest', 'Sand'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    sustainability: {
      ecoRating: 'A',
      carbonFootprint: 4.2,
      materials: [
        { name: 'Recycled Cotton', percentage: 60 },
        { name: 'Recycled Polyester', percentage: 40 },
      ],
      certifications: ['GOTS', 'Fair Trade', 'Climate Neutral'],
    },
    isNew: true,
    isSoldOut: false,
    isLimitedEdition: false,
  },
  {
    id: '2',
    name: 'Organic Tee',
    slug: 'organic-tee',
    price: 1499,
    compareAtPrice: undefined,
    images: ['/images/products/tee-1.jpg'],
    category: 'tees',
    colors: ['White', 'Black', 'Navy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    sustainability: {
      ecoRating: 'A',
      carbonFootprint: 2.1,
      materials: [
        { name: 'Organic Cotton', percentage: 100 },
      ],
      certifications: ['GOTS', 'OEKO-TEX'],
    },
    isNew: false,
    isSoldOut: false,
    isLimitedEdition: false,
  },
  {
    id: '3',
    name: 'Eco Cargo Pants',
    slug: 'eco-cargo-pants',
    price: 5999,
    compareAtPrice: 7499,
    images: ['/images/products/cargo-1.jpg'],
    category: 'bottoms',
    colors: ['Olive', 'Black', 'Sand'],
    sizes: ['28', '30', '32', '34', '36'],
    sustainability: {
      ecoRating: 'B',
      carbonFootprint: 6.8,
      materials: [
        { name: 'Organic Cotton', percentage: 70 },
        { name: 'Hemp', percentage: 30 },
      ],
      certifications: ['GOTS'],
    },
    isNew: false,
    isSoldOut: false,
    isLimitedEdition: false,
  },
  {
    id: '4',
    name: 'Limited Drop Jacket',
    slug: 'limited-drop-jacket',
    price: 11999,
    compareAtPrice: undefined,
    images: ['/images/products/jacket-1.jpg'],
    category: 'outerwear',
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    sustainability: {
      ecoRating: 'A',
      carbonFootprint: 8.5,
      materials: [
        { name: 'Recycled Nylon', percentage: 100 },
      ],
      certifications: ['bluesign', 'Climate Neutral'],
    },
    isNew: true,
    isSoldOut: false,
    isLimitedEdition: true,
  },
  {
    id: '5',
    name: 'Hemp Beanie',
    slug: 'hemp-beanie',
    price: 999,
    compareAtPrice: undefined,
    images: ['/images/products/beanie-1.jpg'],
    category: 'accessories',
    colors: ['Black', 'Charcoal', 'Olive', 'Cream'],
    sizes: ['One Size'],
    sustainability: {
      ecoRating: 'A',
      carbonFootprint: 0.8,
      materials: [
        { name: 'Organic Hemp', percentage: 70 },
        { name: 'Organic Cotton', percentage: 30 },
      ],
      certifications: ['GOTS'],
    },
    isNew: false,
    isSoldOut: false,
    isLimitedEdition: false,
  },
  {
    id: '6',
    name: 'Vintage Wash Crewneck',
    slug: 'vintage-wash-crewneck',
    price: 3499,
    compareAtPrice: undefined,
    images: ['/images/products/crew-1.jpg'],
    category: 'sweatshirts',
    colors: ['Washed Black', 'Washed Blue', 'Washed Olive'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    sustainability: {
      ecoRating: 'B',
      carbonFootprint: 5.2,
      materials: [
        { name: 'Organic Cotton', percentage: 80 },
        { name: 'Recycled Polyester', percentage: 20 },
      ],
      certifications: ['OEKO-TEX'],
    },
    isNew: false,
    isSoldOut: false,
    isLimitedEdition: false,
  },
  {
    id: '7',
    name: 'Deadstock Joggers',
    slug: 'deadstock-joggers',
    price: 3999,
    compareAtPrice: undefined,
    images: ['/images/products/joggers-1.jpg'],
    category: 'bottoms',
    colors: ['Black', 'Heather Grey'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    sustainability: {
      ecoRating: 'A',
      carbonFootprint: 3.5,
      materials: [
        { name: 'Deadstock Cotton', percentage: 85 },
        { name: 'Elastane', percentage: 15 },
      ],
      certifications: ['Deadstock Certified'],
    },
    isNew: true,
    isSoldOut: false,
    isLimitedEdition: false,
  },
  {
    id: '8',
    name: 'Oversized Graphic Tee',
    slug: 'oversized-graphic-tee',
    price: 1999,
    compareAtPrice: undefined,
    images: ['/images/products/graphic-1.jpg'],
    category: 'tees',
    colors: ['Black', 'White'],
    sizes: ['S', 'M', 'L', 'XL'],
    sustainability: {
      ecoRating: 'B',
      carbonFootprint: 2.8,
      materials: [
        { name: 'Organic Cotton', percentage: 100 },
      ],
      certifications: ['GOTS', 'Water-Based Inks'],
    },
    isNew: false,
    isSoldOut: true,
    isLimitedEdition: false,
  },
]

export const categories = [
  { value: '', label: 'All Categories' },
  { value: 'tees', label: 'T-Shirts' },
  { value: 'hoodies', label: 'Hoodies' },
  { value: 'sweatshirts', label: 'Sweatshirts' },
  { value: 'bottoms', label: 'Bottoms' },
  { value: 'outerwear', label: 'Outerwear' },
  { value: 'accessories', label: 'Accessories' },
]

export const ecoRatings = [
  { value: '', label: 'All Ratings' },
  { value: 'A', label: 'A - Excellent' },
  { value: 'B', label: 'B - Good' },
  { value: 'C', label: 'C - Average' },
]

export const sortOptions = [
  { value: 'newest', label: 'Newest' },
  { value: 'price-asc', label: 'Price: Low to High' },
  { value: 'price-desc', label: 'Price: High to Low' },
  { value: 'eco-rating', label: 'Best Eco Rating' },
]
